export const secondMs = 1000
export const minuteSeconds = 60
export const minuteMs = minuteSeconds * secondMs
export const hourMinutes = 60
export const hourSeconds = hourMinutes * minuteSeconds
export const hourMs = hourMinutes * minuteMs
export const dayHours = 24
export const dayMinutes = dayHours * hourMinutes
export const daySeconds = dayHours * hourSeconds
export const dayMs = dayHours * hourMs
